import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { startGameLoop } from "../game/gameLoop";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  useEffect(() => {
    const identifier = setInterval(() => {
      if (document.readyState === "complete") {
        clearInterval(identifier);
        startGameLoop(window, requestAnimationFrame);
      }
    }, 1000);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
};

export default Home;
